---

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/test*.rb'

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 10

Style/Documentation:
  Enabled: false

# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: double_quotes

# Style/StringLiteralsInInterpolation:
#   Enabled: true
#   EnforcedStyle: double_quotes
